### PR TITLE
Including inactive categories on export

### PR DESCRIPTION
**Pull request by adriancr**
Hi! I used your script today to migrate a category structure from one site to another one. It worked pretty well except that the "inactive" categories were not exported. 

The issue is in the exportCategories.php file, line 72.
You won't get the inactive categories when you try to access the children cats like this:

$children = Mage::getModel('catalog/category')->getCategories($category->getId());

This SO post explains the situation: http://stackoverflow.com/questions/14459550/magento-get-categories-tree-dont-show-hidden-categories

The fix is to get the children categories as a collection like this:
$children = Mage::getModel('catalog/category')
                ->load($category->getId())
                ->getCollection()
                ->addAttributeToSort('position', 'ASC')
                ->addFieldToFilter('parent_id', $category->getId());

Hope it helps!

### CODE REVIEW

**Comment by quafzi** [comment]
@adriancr Why did you close that?

**Comment by adriancr** [comment]
hehe kind of new to github and I made another (unrelated) commit after the pull request, which seems to have been picked up by the pull request. I will be fixing it this week. 

May I ask, how would you send a pull request for a specific commit?

**Comment by quafzi** [comment]
Ah, ok :)

I'd recommend to create a separate branch for this request.

**Comment by adriancr** [comment]
Hi @quafzi!

I have the fix in a separate branch now. Is there a way to edit this pull request to "point" to the new branch or should I make a new pull request?

**Comment by adriancr** [comment]
After making a quick google search it seems that is not possible to change the branch for the pull request. So I'll close this one and create a new pull request.

**Pull request closed without merging**
